#!/bin/sh
git checkout dev
git checkout master
git rm init

npm init
if [ $1 ]; then
	git config user.name "$1"
fi

if [ $2 ]; then
	git config user.email "$2"
fi

git update-ref -d refs/heads/master
rm README.md
git add .
git commit -m "Scaffold Initialized"

git checkout --orphan clean
git rm . -rf
git update-ref -d refs/heads/clean
touch README.md
git add .
git commit -m "Clean master"
git checkout master
git rebase clean

git checkout dev
npm install --save-dev gulp gulp-coffee gulp-cache gulp-coffeelint gulp-util gulp-mocha gulp-rimraf run-sequence coffee-script coffeelint coffeelint-stylish should gulp-exec gulp-rename gulp-uglify
git update-ref -d refs/heads/dev
rm README.md
git add --all .
git commit -m "Scaffold Initialized"
git rebase clean
git remote rm origin
git branch clean -D
