#!/bin/sh
git checkout dev
git checkout master
git remote rm origin
git rm init

echo > README.md

npm init
if [ $1 ]; then
	git config user.name "$1"
fi

if [ $2 ]; then
	git config user.email "$2"
fi

git add .
git commit -m "Initial commit"

git checkout dev

npm install --save-dev gulp gulp-coffee gulp-cache gulp-coffeelint gulp-util gulp-mocha gulp-rimraf run-sequence coffee-script coffeelint coffeelint-stylish should gulp-exec gulp-rename gulp-uglify

git add package.json
git commit -m "Added dev dependencies"
